on:
  schedule:
    - cron: 24 14 * * SAT,SUN
  push:
jobs:
  atcoder_images:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59-vanadium
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium
      - name: generate images
        env:
          ATCODER_USERNAME: atu4403
          ATCODER_STATUS_PATH: images/at_status.png
          ATCODER_GRAPH_PATH: images/at_graph.png
        run: |
          git status
          python atcoder_images.py
          python update.py
          git status
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'update AtCoder images'
          pull_strategy: 'NO-PULL'
