# on:
#   schedule:
#   - cron: 0 0 * * *
on:
  push:
jobs:
  atcoder_images:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59-vanadium
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium
      - name: generate images
        env:
          ATCODER_USERNAME: atu4403
          ATCODER_STATUS_PATH: images/at_status.png
          ATCODER_GRAPH_PATH: images/at_graph.png
        run: |
          python atcoder_images.py
          python update.py
      - name: commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config --local user.name atu4403
            git config --local user.email 73111778+atu4403@users.noreply.github.com
            git add .
            git commit -m "Update images"
            git push origin master
          fi
